comments/urls.py
from django.urls import path
from . import views

app_name = "comments"

urlpatterns = [
    path('', views.CommentCreateView.as_view(), name='comment'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('tweets.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tweets/urls.py
from django.urls import path, include
from . import views
from .views import IndexView,CreateView,DeleteView,UpdateView,DetailView

app_name = 'Tweets'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('tweets/create/', CreateView.as_view(), name='create'),
    path('tweets/<int:pk>/delete', DeleteView.as_view(), name='delete'),
    path('tweets/<int:pk>/update', UpdateView.as_view(), name='update'),
    path('tweets/<int:pk>/', DetailView.as_view(), name='detail'),
    path('tweets/<int:pk>/comments/', include('comments.urls')),
    path('tweets/search_tweets/', views.tweet_search, name='search'),
]

users/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = "users"
urlpatterns = [
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign_in/', LoginView.as_view(template_name='users/sign_in.html',next_page='/'),name='sign_in'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('<int:pk>/', views.UserPageView.as_view(), name='mypage'),
]

comments/models.py
from django.db import models
from django.conf import settings

class Comment(models.Model):
  class Meta:
    db_table = 'comments'
  
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  tweet = models.ForeignKey('tweets.Tweet', on_delete=models.CASCADE)
  text = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.text

tweets/models.py
from django.db import models
from django.conf import settings

class Tweet(models.Model):
  class Meta:
    db_table = 'tweets'

  text = models.TextField(null=False, blank=False)
  image = models.ImageField(upload_to='images/', blank=True, null=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=False)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

# カスタム ユーザーマネージャー
class CustomUserManager(BaseUserManager):
    def create_user(self, email, nickname, password=None, **extra_fields):
        if not email:
            raise ValueError('Email address is required')
        email = self.normalize_email(email)
        user = self.model(email=email, nickname=nickname, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

# カスタム ユーザーモデル
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    nickname = models.CharField(max_length=30, null=False)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nickname']

    objects = CustomUserManager() 

    def __str__(self):
        return self.email

comments/forms.py
from django import forms
from .models import  Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

        labels = {
            'text': 'コメント',
        }

tweets/forms.py
from .models import Tweet
from django import forms

class TweetForm(forms.ModelForm):
    class Meta:
      model = Tweet
      fields = ['text','image']
      widgets = {
         'text': forms.Textarea(attrs={'placeholder': 'Text', 'rows': 10}),
      }
      labels = {
         'text': 'テキスト',
      }

class SearchForm(forms.Form):
    keyword = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': '投稿を検索する',
            'class': 'search-input'
        })
    )

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()  # カスタムユーザーモデルを取得
        fields = ('email', 'nickname',)  # 'email' と 'nickname' を追加

comments/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Comment
from .forms import CommentForm
from tweets.models import Tweet

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        tweet_id = self.kwargs['pk']
        tweet = get_object_or_404(Tweet, pk=tweet_id)
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.tweet = tweet
        comment.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        tweet_id = self.kwargs['pk']
        return redirect('Tweets:detail', pk=tweet_id)

    def get_success_url(self):
        return reverse('Tweets:detail', kwargs={'pk': self.kwargs['pk']})

tweets/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView,CreateView,DeleteView,UpdateView,DetailView
from django.urls import reverse_lazy
from .models import Tweet
from .forms import TweetForm, SearchForm
from django.views.generic.edit import FormMixin
from comments.forms import CommentForm
from comments.models import Comment

class IndexView(ListView, FormMixin):
    model = Tweet
    template_name = 'tweets/index.html'
    context_object_name = 'tweets'
    ordering = '-created_at'
    form_class = SearchForm

class CreateView(CreateView):
    form_class = TweetForm
    template_name = 'tweets/create.html'
    success_url = reverse_lazy("Tweets:index")

    def form_valid(self, form):
        tweet = form.save(commit=False)
        tweet.user = self.request.user
        tweet.save()
        return super().form_valid(form)

class DeleteView(DeleteView):
    model = Tweet
    success_url = reverse_lazy('Tweets:index')

class UpdateView(UpdateView):
    model = Tweet
    form_class = TweetForm
    template_name = 'tweets/update.html'
    success_url = reverse_lazy('Tweets:index')

    def get_object(self, queryset=None):
        return get_object_or_404(Tweet, pk=self.kwargs['pk'])

class DetailView(FormMixin,DetailView):
    model = Tweet
    template_name = 'tweets/detail.html'
    form_class = CommentForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = Comment.objects.filter(tweet=self.object).order_by('-created_at')
        context['comments'] = comments
        context['form'] = self.get_form()
        return context

def tweet_search(request):
    form = SearchForm(request.GET or None)
    if form.is_valid():
        keyword = form.cleaned_data.get('keyword', '')
        tweets = Tweet.objects.filter(text__icontains=keyword)
    else:
        tweets = Tweet.objects.all()
    return render(request, 'tweets/search.html', {'form': form, 'tweets': tweets})

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import login,get_user_model
from .forms import CustomUserCreationForm
from django.views.generic import ListView
from django.shortcuts import get_object_or_404
from tweets.models import Tweet

class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('Tweets:index')  # 登録完了後にリダイレクトするURL
    template_name = 'users/sign_up.html'

    def form_valid(self, form):
        # バリデーションが成功したら、ユーザーを作成してそのユーザーでログインさせる
        response = super().form_valid(form)
        user = form.save()
        login(self.request, user)
        return response

class UserPageView(ListView):
    model = Tweet
    template_name = 'users/mypage.html'
    context_object_name = 'tweets'

    def get_queryset(self):
        user_id = self.kwargs.get('pk')
        self.user = get_object_or_404(get_user_model(), pk=user_id)
        return Tweet.objects.filter(user=self.user).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_user'] = self.user
        return context

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Pictweet</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/">PicTweet</a></h1>
      {% if user.is_authenticated %}
        <div class="user_nav grid-6">
          <span>{{ user.nickname }}
            <ul class="user__info">
                <li>
                  <a href="{% url 'users:mypage' user.pk%}">マイページ</a>
                  <a href="{% url 'users:logout' %}">ログアウト</a>
                </li>
            </ul>
          </span>
          <a class="post" href="{% url 'Tweets:create' %}">投稿する</a>
      {% else %}
        <div class="grid-6">
          <a class="post" href={% url "users:sign_in" %}>ログイン</a>
          <a class="post" href={% url "users:sign_up" %}>新規登録</a>
        </div>
      {% endif %}
    </div>
  </header>


  {% block content %}{% endblock content %}

  <footer>
    <p>
    Copyright PicTweet 2023.
    </p>
  </footer>

</body>
</html>

templates/comments/comment.html
{% load static %}

<div class="container">
  {% if user.is_authenticated %}
  <form method="post" enctype="multipart/form-data" action="{% url 'Tweets:comments:comment' pk=tweet.id %}">
          {% csrf_token %}
          {{ form.text }}
          <input type="submit" value="SEND">
  </form>
  {% else %}
    <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
  {% endif %}

  <div class="comments">
    <h4>＜コメント一覧＞</h4>
    {% for comment in comments %}
    <p>
       <a href="{% url 'users:mypage' comment.user.pk %}">{{ comment.user.nickname }}</a>
       {{ comment.text }}
    </p>
    {% endfor %}

</div>
</div>

templates/tweets/_form.html
{% if form.errors %}
  <div class="error-summary">
      <ul>
          {% for field in form %}
              {% for error in field.errors %}
                  <li><strong>{{ field.label }}:</strong> {{ error }}</li>
              {% endfor %}
          {% endfor %}
      </ul>
  </div>
{% endif %}
{{ form.text }}
{{ form.image }}
<input type="submit" value="SEND">

templates/tweets/_tweet_list.html
{% load static %}

{% for tweet in tweets %}
  <div class="content_post" style="{% if tweet.image %} background-image: url('{{ tweet.image.url }}');{% endif %}">
    <div class="more">
      <span><img src="{% static 'images/arrow_top.png' %}"></span>
      <ul class="more_list">
        <li>
          <a href="{% url 'Tweets:detail' tweet.id %}" class="detail-btn">詳細</a>
        </li>
        {% if tweet.user == request.user %}
        <li>
          <form action="{% url 'Tweets:delete' tweet.id %}" method="post">
          {% csrf_token %}
            <input type="submit" class="delete-btn" value="削除">
          </form>
        </li>
        <li>
          <a href="{% url 'Tweets:update' tweet.id %}" class="update-btn">編集</a>
        </li>
        {% endif %}
      </ul>
    </div>
    <p>{{ tweet.text }}</p>
    <span class="name"><a href="{% url 'users:mypage' tweet.user.pk %}">
    <span>投稿者</span>{{ tweet.user.nickname }}</a>
    </span>
  </div>
{% endfor %}

templates/tweets/create.html
{% extends "base.html" %}
{% block content %}

<form method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    <div class="contents row">
        <div class="container">
            <h3>投稿する</h3>
            {% include 'tweets/_form.html' %}
        </div>
    </div>
</form>

{% endblock content %}

templates/tweets/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="contents row">
    <div class="content_post" style="{% if tweet.image %}background-image: url('{{ tweet.image.url }}');{% endif %}" >
        {% if tweet.user == request.user %}
        <div class="more">
            <span><img src="{% static 'images/arrow_top.png' %}"></span>
            <ul class="more_list">
                <li>
                    <form action="{% url 'Tweets:delete' tweet.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="delete-btn" value="削除">
                    </form>
                </li>
                <li>
                  <a href="{% url 'Tweets:update' tweet.id %}" class="update-btn">編集</a>
                </li>
            </ul>
        </div>
        {% endif %}
        <p>{{ tweet.text }}</p>
        <span class="name"><a href="{% url 'users:mypage' tweet.user.pk %}">
          <span>投稿者</span>{{ tweet.user.nickname }}</a>
        </span>
    </div>
    {% include 'comments/comment.html' %}
</div>

{% endblock content %}

templates/tweets/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<form action="{% url 'Tweets:search' %}" method="get" class="search-form">
  {{ form.keyword }}
  <input type="submit" class="search-btn" value="検索">
</form>

<h1>Top page</h1> 
<div class="contents row">
  {% include 'tweets/_tweet_list.html' %}
</div>

{% endblock content %}

templates/tweets/search.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<form action="{% url 'Tweets:search' %}" method="get" class="search-form">
  {{ form.keyword }}
  <input type="submit" class="search-btn" value="検索">
</form>

<div class="contents row">
  {% include 'tweets/_tweet_list.html' %}
</div>

{% endblock content %}

templates/tweets/update.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="contents row">
      <div class="container">
          <h3>編集する</h3>
          {% include 'tweets/_form.html' %}
      </div>
  </div>
</form>

{% endblock content %}

templates/users/mypage.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="contents row">
  <p>{{ profile_user.nickname }}さんの投稿一覧</p>
  {% include 'tweets/_tweet_list.html' %}
</div>

{% endblock content %}

templates/users/sign_in.html
{% extends "base.html" %}
{% block content %}

<form method="post">
  {% csrf_token %}

    <div class="contents row">
        <div class="container">
            <h2>Log in</h2>
            <div class="field">
                {{ form.username.label_tag }}
                {{ form.username }}
                {% if form.username.errors %}
                <ul class="errorlist">
                    {% for error in form.username.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="field">
                {{ form.password.label_tag  }}<a>(英数字含む8文字以上)</a>
                {{ form.password }}
                {% if form.password.errors %}
                <ul class="errorlist">
                    {% for error in form.password.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="actions">
                <input type="submit" value="Log in">
            </div>
        </div>
    </div>

</form>
{% endblock content %}

templates/users/sign_up.html
{% extends "base.html" %}
{% block content %}

<form method="post">
  {% csrf_token %}

    <div class="contents row">
        <div class="container">
            <h2>Sign up</h2>
            {% if form.errors %}
            <div class="error">
                <p>入力にエラーがあります。もう一度ご確認ください。</p>
                {{ form.non_field_errors }}
            </div>
        {% endif %}
            <div class="field">
                {{ form.nickname.label_tag }}
                {{ form.nickname }}
                {% if form.nickname.errors %}
                <ul class="errorlist">
                    {% for error in form.nickname.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="field">
                {{ form.email.label_tag  }}
                {{ form.email }}
                {% if form.email.errors %}
                <ul class="errorlist">
                    {% for error in form.email.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="field">
                {{ form.password1.label_tag  }}<a>(英数字含む8文字以上)</a>
                {{ form.password1 }}
                {% if form.password1.errors %}
                <ul class="errorlist">
                    {% for error in form.password1.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="field">
                {{ form.password2.label_tag  }}
                {{ form.password2 }}
                {% if form.password2.errors %}
                <ul class="errorlist">
                    {% for error in form.password2.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            <div class="actions">
                <input type="submit" value="Sign Up">
            </div>
        </div>
    </div>

</form>
{% endblock content %}